start_role: DocumentationLeader
steps:
  - step: 需求分析与任务规划
    actor: DocumentationLeader
    output:
      - 质量标准定义
    substeps: []
  - step: 项目背景编写
    actor: TechnicalWriter
    output:
      - 项目背景
  - step: 项目目标
    actor: TechnicalWriter
    output:
      - 项目目标
  - step: 项目核心功能
    actor: CodeAnalyzer
    output:
      - 项目核心功能
  #安装步骤
  - step: 安装步骤
    actor: CodeAnalyzer
    input:
      - 项目核心功能
    output:
      - 安装步骤
  # 配置指南
  - step: 配置指南
    actor: CodeAnalyzer
    input:
      - 项目核心功能
    output:
      - 配置指南
  # 使用指南
  - step: 使用指南
    actor: CodeAnalyzer
    input:
      - 代码仓库地址
    output:
      - 使用指南
